apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-08T04:55:02Z"
deprecatedLastTimestamp: "2024-01-08T04:55:02Z"
deprecatedSource:
  component: deployment-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-08T04:55:02Z"
  name: katafygio.17a8464096ceda5f
  namespace: default
  uid: 51b1512f-beb5-4523-b392-30454ed4e349
note: Scaled down replica set katafygio-7f46996756 to 0 from 1
reason: ScalingReplicaSet
regarding:
  apiVersion: apps/v1
  kind: Deployment
  name: katafygio
  namespace: default
  resourceVersion: "1259962"
  uid: d71f94ac-73a0-4630-a57c-701d904e3f73
type: Normal
