apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-08T04:55:02Z"
deprecatedLastTimestamp: "2024-01-08T04:55:02Z"
deprecatedSource:
  component: replicaset-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-08T04:55:02Z"
  name: katafygio-7f46996756.17a84640978db7dd
  namespace: default
  uid: a03605f0-a9b2-4ee5-bbe7-173c766982f5
note: 'Deleted pod: katafygio-7f46996756-ndrgc'
reason: SuccessfulDelete
regarding:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: katafygio-7f46996756
  namespace: default
  resourceVersion: "1259963"
  uid: b24826f9-cc5a-454e-9d3b-5ccbc5af68da
type: Normal
