apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-05T12:08:11Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{katafygio}
  kind: Pod
  name: katafygio-7f46996756-ndrgc
  namespace: default
  resourceVersion: "1254525"
  uid: 97a54d9c-26a7-462c-9561-f70b4abfbab7
kind: Event
lastTimestamp: "2024-01-05T12:08:11Z"
message: Pulling image "sharmag07/katafygio:k13"
metadata:
  creationTimestamp: "2024-01-05T12:08:11Z"
  name: katafygio-7f46996756-ndrgc.17a77225f403c3ed
  namespace: default
  uid: e786f2d6-8c9a-4479-9407-23c426bf4373
reason: Pulling
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
