apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-05T12:03:11Z"
involvedObject:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: katafygio-7d7fcd567
  namespace: default
  resourceVersion: "1254195"
  uid: fdd570a5-c560-4b24-a645-cb85e779b2a6
kind: Event
lastTimestamp: "2024-01-05T12:03:11Z"
message: 'Deleted pod: katafygio-7d7fcd567-9sblx'
metadata:
  creationTimestamp: "2024-01-05T12:03:11Z"
  name: katafygio-7d7fcd567.17a771e03618057f
  namespace: default
  uid: 03bacd7f-f63f-4d2c-be2b-7638c4bd4348
reason: SuccessfulDelete
reportingComponent: ""
reportingInstance: ""
source:
  component: replicaset-controller
type: Normal
