apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-05T12:08:17Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{katafygio}
  kind: Pod
  name: katafygio-7f46996756-ndrgc
  namespace: default
  resourceVersion: "1254525"
  uid: 97a54d9c-26a7-462c-9561-f70b4abfbab7
kind: Event
lastTimestamp: "2024-01-05T12:08:17Z"
message: Started container katafygio
metadata:
  creationTimestamp: "2024-01-05T12:08:17Z"
  name: katafygio-7f46996756-ndrgc.17a7722763c56d53
  namespace: default
  uid: 7776035e-e2a9-40fd-9b40-9a83536e3cc7
reason: Started
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
