apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"katafygio","chart":"katafygio-0.5.1","heritage":"Helm","release":"katafygio"},"name":"katafygio","namespace":"default"}}
    meta.helm.sh/release-name: katafygio
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-10-26T08:14:20Z"
  labels:
    app: katafygio
    app.kubernetes.io/managed-by: Helm
    chart: katafygio-0.5.1
    heritage: Helm
    release: katafygio
  name: katafygio
  namespace: default
  uid: cd8f353d-d211-4ca2-8f67-7ad46c15aa5f
